import "@/styles/globals.css";
import Sidebar from "@/components/Sidebar";
import SidebarProvider from "@/context/SidebarContext";
import SessionWrapper from "@/context/SessionWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className="flex overflow-hidden">
          <SidebarProvider>
            <Sidebar />
          </SidebarProvider>
          <div className="w-4/5">{children}</div>
        </body>
      </html>
    </SessionWrapper>
  );
}
